### ISSUE TITLE
Mysterious error

### ISSUE THREAD

**Issue by kiddo18** [mhegde/base-editor-design-tool#2]
Hi Mudra,

I'm just wondering if you know what this error is. I simply just `git clone` your repo and ran 
`python base_editing_guide_designs.py --input-file ./Sample_data/GFP.fasta --variant-file ../ClinVar/variant_summary.txt --input-type nuc --be-type BE3 --output-name GFP`

But it showed this error. I tried looking through the file, but don't really understand where the bug is coming from. Are you familiar with this by any chance? Thank you! :)

`/Users/base_editor_screen/base-editor-design-tool/base_editing_guide_designs.py:446: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  parsed_variant_df.loc[:,'RefSeqID'] = parsed_variant_df.loc[:,'Name'].str.split('(',1).str[0]
Designing for GFP
Traceback (most recent call last):
  File "/Users/base_editor_screen/base-editor-design-tool/base_editing_guide_designs.py", line 1215, in <module>
    val = design_sgrnas(gene_name, assembly, chromosome, gene_id, w, tr_seq, abs_pos_map, fs, cds_map, utr, tr, pam, exons, gene_strand, edit, window, cds_sequence, len(pam), sg_len, cds_start_exon, w_error, w_clin, gene_variant_df, aa_map, input_type, intron_buffer, filter_gc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/base_editor_screen/base-editor-design-tool/base_editing_guide_designs.py", line 971, in design_sgrnas
    context_for_trans, cds_pos, i_count = get_context_for_trans(ct_index, pos+sg_len+pam_len+3, abs_pos, cds_map, fs, sgrna_context)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/base_editor_screen/base-editor-design-tool/base_editing_guide_designs.py", line 832, in get_context_for_trans
    gen_pos = abs_pos.keys()[abs_pos.values().index(ct_index)]
                             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict_values' object has no attribute 'index'`

**Comment by kiddo18** [comment]
python version 3.11
biopython version v1.81

**Comment by mhegde** [comment]
Hi, please use Python 2.7. That should resolve the error. The syntax is slightly different in Python3.

**Comment by kiddo18** [comment]
That works! Thank you for sharing this tool!
